baseURL = 'https://nsd-singbar.yeojido.io/'
languageCode = 'ko-KR'
title = '낙성대 노래빠 누벨 NOUVEL 최신 정보'

[params]
  isAdsEnabled = true
  adsTelegramId = "ggyuvely"

  description = '낙성대 노래빠 누벨은 서울 관악구 봉천동에 있다.'
  author = '누벨'
  datePublished = "2026-08-18T08:50:00+09:00"
  dateModified = "2026-08-18T08:50:00+09:00"
  [params.store]
  tel = "010-7456-5410"
  location = "낙성대"
  locationEn = "NSD"
  name = "누벨"
  nameEn = "NOUVEL"
  category = "노래빠"
  categoryEn = "Singbar"
  address = "서울 관악구 봉천동"
  googleMapSrc = "https://www.google.com/maps?q=서울+관악구+봉천동&output=embed"
	[params.store.social.kakaoTalk]
	  id = ""
	  link = ""
	[params.store.social.telegram]
    id = ""
    link = ""

enableRobotsTXT = false
cleanDestinationDir = true

[build]
  [build.buildStats]
    enable = true
  [[build.cachebusters]]
    source = 'assets/notwatching/hugo_stats\.json'
    target = 'css'
  [[build.cachebusters]]
    source = '(postcss|tailwind)\.config\.js'
    target = 'css'
[module]
  [[module.mounts]]
    source = 'assets'
    target = 'assets'
  [[module.mounts]]
    disableWatch = true
    source = 'hugo_stats.json'
    target = 'assets/notwatching/hugo_stats.json'

[caches]
  [caches.images]
    dir = ':cacheDir/images'
